ZSH=$HOME/.oh-my-zsh
ZSH_THEME=bureau
DISABLE_AUTO_UPDATE='true'
DISABLE_CORRECTION='true'

plugins=(
  autojump,
  command_not_found,
  django,
)

source $ZSH/oh-my-zsh.sh

export EDITOR=vim
export VIRTUAL_ENV_DISABLE_PROMPT=1

[ -f $HOME/.ansible_zshrc ] && . $HOME/.ansible_zshrc
[ -f $HOME/.web_zshrc ] && . $HOME/.web_zshrc
