- name: Setting up development secrets file
  copy: src=development_secrets/env dest=/goma/secret/env
    owner=goma group=goma mode=600
  when: env == 'development'
- name: Setting up deployed secrets file
  copy: src={{secrets_dir}}/env dest=/goma/secret/env
    owner=goma group=goma mode=600
  when: deployed
